// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmpwcinxesdfefbmszug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtcHdjaW54ZXNkZmVmYm1zenVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODAxNDEsImV4cCI6MjA2NzY1NjE0MX0.kzAAtsPFbePGr8mQWwfTVUVZgKrMD0Mx-GHI3zVAYJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});